### ISSUE TITLE
error in the AddListing.js in the classified ads service

### ISSUE THREAD

**Issue by MohamedAlaa** [parkroolucas/microservices-demo#3]
the following line needs to be changed from

```
import useForm from "react-hook-form";
```

To

```
import { useForm } from "react-hook-form";
```

**Comment by MohamedAlaa** [comment]
I'm using react-hook-form version 4.4.2

**Comment by parkroolucas** [comment]
Yep, v4 got released not long after I made this video series. There might be a few other things as well (I'm not sure), make sure you check the changelog.
